import {
  ChangeDetectionStrategy,
  Component,
  computed,
  DestroyRef,
  inject,
  OnInit,
  signal,
} from '@angular/core';
import { takeUntilDestroyed } from '@angular/core/rxjs-interop';
import { NgTemplateOutlet } from '@angular/common';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { ActivatedRoute, Router } from '@angular/router';
import { MatButtonModule } from '@angular/material/button';
import { DateAdapter, provideNativeDateAdapter } from '@angular/material/core';
import { MatDatepickerModule } from '@angular/material/datepicker';
import { MatIconModule } from '@angular/material/icon';
import { finalize } from 'rxjs';
import { DMY_DATE_FORMATS, DmyDateAdapter } from '../../shared/date/dmy-date-adapter';
import { OrderDocumentsComponent } from './order-documents/order-documents';
import { NotificationService } from '../../core/services/notification.service';
import { FieldComponent } from '../../shared/components/field/field';
import { PageHeaderComponent } from '../../shared/components/page-header/page-header';
import { SelectComponent, SelectOption } from '../../shared/components/select/select';
import { ConfirmService } from '../../shared/services/confirm.service';
import { DropdownService } from '../../shared/services/dropdown.service';
import { FtpOrderService } from './ftp-order.service';

@Component({
  selector: 'app-ftp-order-entry',
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [
    ReactiveFormsModule,
    NgTemplateOutlet,
    PageHeaderComponent,
    FieldComponent,
    SelectComponent,
    MatButtonModule,
    MatIconModule,
    MatDatepickerModule,
    OrderDocumentsComponent,
  ],
  // dd-MMM-yyyy datepicker, scoped to this screen.
  providers: [
    provideNativeDateAdapter(DMY_DATE_FORMATS),
    { provide: DateAdapter, useClass: DmyDateAdapter },
  ],
  templateUrl: './ftp-order-entry.html',
  styleUrl: './ftp-order-entry.scss',
})
export class FtpOrderEntryComponent implements OnInit {
  private readonly fb = inject(FormBuilder);
  private readonly destroyRef = inject(DestroyRef);
  private readonly dropdowns = inject(DropdownService);
  private readonly service = inject(FtpOrderService);
  private readonly notify = inject(NotificationService);
  private readonly confirm = inject(ConfirmService);
  private readonly router = inject(Router);
  private readonly route = inject(ActivatedRoute);

  protected readonly saving = signal(false);
  protected readonly recordId = signal(0);
  protected readonly isEdit = computed(() => this.recordId() > 0);

  /** Edit-mode left tab: order form vs the upload-document panel. */
  protected readonly tab = signal<'details' | 'documents'>('details');

  // Dropdown option lists
  protected readonly clientOptions = signal<SelectOption[]>([]);
  protected readonly bankOptions = signal<SelectOption[]>([]);
  protected readonly txnOptions = signal<SelectOption[]>([]);
  protected readonly currencyOptions = signal<SelectOption[]>([]);
  protected readonly impExpOptions: SelectOption[] = [
    { value: 'Import', label: 'Import' },
    { value: 'Export', label: 'Export' },
  ];
  protected readonly whatToDoOptions: SelectOption[] = [
    { value: 'Buy', label: 'Buy' },
    { value: 'Sell', label: 'Sell' },
  ];
  protected readonly windowFixOptions: SelectOption[] = [
    { value: 'Window', label: 'Window' },
    { value: 'Fix', label: 'Fix' },
  ];

  protected readonly form = this.fb.nonNullable.group({
    client: this.fb.control<number | null>(null, [Validators.required]),
    clientBank: this.fb.control<number | null>(null),
    transactionType: this.fb.control<number | null>(null, [Validators.required]),
    // Auto-generated by the server — shown read-only, first in the form.
    orderNumber: this.fb.control({ value: '', disabled: true }),
    importExport: this.fb.control<string | null>(null),
    currency: this.fb.control<string | null>(null, [Validators.required]),
    amount: this.fb.control<number | null>(null, [Validators.required]),
    whatToDo: this.fb.control<string | null>(null),
    maturityDate: this.fb.control<Date | null>(null),
    windowFix: this.fb.control<string | null>(null),
    bookingRate: this.fb.control<number | null>(null),
    forwardContactNo: [''],
    outstandingAmount: this.fb.control<number | null>(null),
  });

  /** The currently-selected transaction type as a signal (for the conditional block). */
  private readonly txnTypeValue = signal<number | null>(null);

  /** True when the selected transaction type is a Forward Cancellation. */
  protected readonly isForwardCancellation = computed(() => {
    const id = this.txnTypeValue();
    const opt = this.txnOptions().find((o) => o.value === id);
    return !!opt && /cancel/i.test(opt.label);
  });

  ngOnInit(): void {
    this.dropdowns.get('Client').subscribe((o) => this.clientOptions.set(o));
    this.dropdowns.get('TransactionType').subscribe((o) => this.txnOptions.set(o));
    this.dropdowns.get('Currency').subscribe((o) => this.currencyOptions.set(o));

    // Client → Client Bank cascade. (DestroyRef passed explicitly because
    // takeUntilDestroyed() needs an injection context, which ngOnInit is not.)
    this.form.controls.client.valueChanges
      .pipe(takeUntilDestroyed(this.destroyRef))
      .subscribe((clientId) => {
        this.form.controls.clientBank.setValue(null, { emitEvent: false });
        this.bankOptions.set([]);
        if (clientId)
          this.dropdowns.get('ClientBank', clientId).subscribe((o) => this.bankOptions.set(o));
      });

    this.form.controls.transactionType.valueChanges
      .pipe(takeUntilDestroyed(this.destroyRef))
      .subscribe((v) => this.txnTypeValue.set(v));

    const idParam = this.route.snapshot.paramMap.get('id');
    const id = idParam ? Number(idParam) : 0;
    if (id > 0) {
      this.recordId.set(id);
      this.loadOrder(id);
    }
  }

  private loadOrder(id: number): void {
    this.service.getById(id).subscribe((o) => {
      this.form.patchValue({
        transactionType: o.transactionTypeID ?? null,
        orderNumber: o.orderNumber ?? '',
        importExport: o.impExp ?? null,
        currency: o.currencyCode ?? null,
        amount: o.amount ?? null,
        whatToDo: o.buySell ?? null,
        maturityDate: o.maturityDate ? new Date(o.maturityDate) : null,
        windowFix: o.dateSelectionType ?? null,
        bookingRate: o.bookingRate ?? null,
        forwardContactNo: o.forwardContactNo ?? '',
        outstandingAmount: o.outstandingAmount ?? null,
      });
      this.txnTypeValue.set(o.transactionTypeID ?? null);

      // Restore client + bank without firing the cascade reset.
      this.form.controls.client.setValue(o.clientID ?? null, { emitEvent: false });
      if (o.clientID) {
        this.dropdowns.get('ClientBank', o.clientID).subscribe((opts) => {
          this.bankOptions.set(opts);
          this.form.controls.clientBank.setValue(o.clientBank ?? null, { emitEvent: false });
        });
      }
    });
  }

  protected submit(): void {
    if (this.form.invalid || this.saving()) {
      this.form.markAllAsTouched();
      this.notify.error('Please fill the required fields.');
      return;
    }
    this.confirm
      .confirm({
        title: 'Book this order?',
        message: 'The order will be saved to the order booking.',
        confirmText: 'Book Order',
        icon: 'check_circle',
      })
      .subscribe((ok) => {
        if (ok) this.book();
      });
  }

  private book(): void {
    this.saving.set(true);
    const v = this.form.getRawValue();
    const fields: Record<string, string | null> = {
      Action: this.isEdit() ? 'UPDATE' : 'INSERT',
      RecordID: this.isEdit() ? String(this.recordId()) : null,
      ClientID: numStr(v.client),
      ClientBank: numStr(v.clientBank),
      TransactionTypeID: numStr(v.transactionType),
      OrderNumber: v.orderNumber || null,
      ImpExp: v.importExport,
      CurrencyCode: v.currency,
      Amount: numStr(v.amount),
      BuySell: v.whatToDo,
      MaturityDate: toDmy(v.maturityDate),
      DateSelectionType: v.windowFix,
      BookingRate: numStr(v.bookingRate),
      ForwardContactNo: this.isForwardCancellation() ? v.forwardContactNo || null : null,
      OutstandingAmount: this.isForwardCancellation() ? numStr(v.outstandingAmount) : null,
      ActiveStatus: 'New',
    };

    this.service
      .book(fields)
      .pipe(finalize(() => this.saving.set(false)))
      .subscribe((res) => {
        if (res.success) {
          this.notify.success(res.message || 'Order booked successfully.');
          this.router.navigate(['/ftp-order-entry']);
        } else {
          this.notify.error(res.message || 'Could not book the order.');
        }
      });
  }

  protected clear(): void {
    this.form.reset();
    this.bankOptions.set([]);
    this.txnTypeValue.set(null);
  }

  protected cancel(): void {
    this.router.navigate(['/ftp-order-entry']);
  }
}

function numStr(v: number | null | undefined): string | null {
  return v === null || v === undefined ? null : String(v);
}

/** Date → dd/MM/yyyy (style 103, matching the booking proc). */
function toDmy(date: Date | null): string | null {
  if (!date) return null;
  const d = String(date.getDate()).padStart(2, '0');
  const m = String(date.getMonth() + 1).padStart(2, '0');
  return `${d}/${m}/${date.getFullYear()}`;
}
